spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_database
    username: root
    password: new_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: UserPostService

server:
  port: 8080
